#include "oceansystem.h"

#include "assets.h"
#include "cameracomponent.h"
#include "cgltf.h"
#include "meshsystem.h"
#include "ocean.hlsli"
#include "oceancomponent.h"
#include "profiling.h"
#include "rendersystem.h"
#include "tbcommon.h"
#include "transformcomponent.h"
#include "viewsystem.h"
#include "world.h"

// Ignore some warnings for the generated headers
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wmissing-variable-declarations"
#endif
#include "depthcopy_frag.h"
#include "depthcopy_vert.h"
#include "ocean_frag.h"
#include "ocean_vert.h"
#include "oceanprepass_frag.h"
#include "oceanprepass_vert.h"
#ifdef __clang__
#pragma clang diagnostic pop
#endif

typedef struct DepthCopyBatch {
  VkPipeline pipeline;
  VkPipelineLayout layout;
  VkViewport viewport;
  VkRect2D scissor;
  VkDescriptorSet depth_src_set;
} DepthCopyBatch;

typedef struct OceanDrawBatch {
  VkPipeline pipeline;
  VkPipelineLayout layout;
  VkViewport viewport;
  VkRect2D scissor;
  OceanPushConstants consts;
  VkDescriptorSet view_set;
  VkDescriptorSet ocean_set;
  VkBuffer geom_buffer;
  VkIndexType index_type;
  uint32_t index_count;
  uint64_t pos_offset;
  uint64_t uv_offset;
} OceanDrawBatch;

void depth_copy_record(VkCommandBuffer buffer, uint32_t batch_count,
                       const void *batches) {
  TracyCZoneNC(ctx, "Depth Copy Record", TracyCategoryColorRendering, true);

  if (batch_count == 0) {
    TracyCZoneEnd(ctx);
    return;
  }

  if (batch_count > 1) {
    TB_CHECK(false, "Only expecting one batch");
    TracyCZoneEnd(ctx);
    return;
  }

  const DepthCopyBatch *batch = (const DepthCopyBatch *)batches;

  VkPipelineLayout layout = batch->layout;

  vkCmdBindPipeline(buffer, VK_PIPELINE_BIND_POINT_GRAPHICS, batch->pipeline);

  vkCmdSetViewport(buffer, 0, 1, &batch->viewport);
  vkCmdSetScissor(buffer, 0, 1, &batch->scissor);

  vkCmdBindDescriptorSets(buffer, VK_PIPELINE_BIND_POINT_GRAPHICS, layout, 0, 1,
                          &batch->depth_src_set, 0, NULL);

  // Just drawing a fullscreen triangle that's generated by the vertex shader
  vkCmdDrawIndexed(buffer, 3, 1, 0, 0, 0);

  TracyCZoneEnd(ctx);
}

void ocean_pass_record(VkCommandBuffer buffer, uint32_t batch_count,
                       const void *batches) {
  TracyCZoneNC(ctx, "Ocean Record", TracyCategoryColorRendering, true);

  const OceanDrawBatch *ocean_batches = (const OceanDrawBatch *)batches;
  for (uint32_t batch_idx = 0; batch_idx < batch_count; ++batch_idx) {
    const OceanDrawBatch *batch = &ocean_batches[batch_idx];
    VkPipelineLayout layout = batch->layout;
    VkBuffer geom_buffer = batch->geom_buffer;

    vkCmdBindPipeline(buffer, VK_PIPELINE_BIND_POINT_GRAPHICS, batch->pipeline);

    vkCmdSetViewport(buffer, 0, 1, &batch->viewport);
    vkCmdSetScissor(buffer, 0, 1, &batch->scissor);

    vkCmdBindDescriptorSets(buffer, VK_PIPELINE_BIND_POINT_GRAPHICS, layout, 1,
                            1, &batch->view_set, 0, NULL);
    vkCmdBindDescriptorSets(buffer, VK_PIPELINE_BIND_POINT_GRAPHICS, layout, 0,
                            1, &batch->ocean_set, 0, NULL);
    vkCmdPushConstants(buffer, layout, VK_SHADER_STAGE_VERTEX_BIT, 0,
                       sizeof(OceanPushConstants), &batch->consts);

    vkCmdBindIndexBuffer(buffer, geom_buffer, 0, batch->index_type);
    vkCmdBindVertexBuffers(buffer, 0, 1, &geom_buffer, &batch->pos_offset);
    // vkCmdBindVertexBuffers(buffer, 1, 1, &geom_buffer, &batch->uv_offset);

    vkCmdDrawIndexed(buffer, batch->index_count, 1, 0, 0, 0);
  }
  TracyCZoneEnd(ctx);
}

VkResult create_depth_pipeline(RenderSystem *render_system, VkRenderPass pass,
                               VkPipelineLayout pipe_layout,
                               VkPipeline *pipeline) {
  VkResult err = VK_SUCCESS;

  VkShaderModule depth_vert_mod = VK_NULL_HANDLE;
  VkShaderModule depth_frag_mod = VK_NULL_HANDLE;

  {
    VkShaderModuleCreateInfo create_info = {
        .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
    };
    create_info.codeSize = sizeof(depthcopy_vert);
    create_info.pCode = (const uint32_t *)depthcopy_vert;
    err = tb_rnd_create_shader(render_system, &create_info, "Depth Copy Vert",
                               &depth_vert_mod);
    TB_VK_CHECK_RET(err, "Failed to load ocean vert shader module", err);

    create_info.codeSize = sizeof(depthcopy_frag);
    create_info.pCode = (const uint32_t *)depthcopy_frag;
    err = tb_rnd_create_shader(render_system, &create_info, "Depth Copy Frag",
                               &depth_frag_mod);
    TB_VK_CHECK_RET(err, "Failed to load depth frag shader module", err);
  }

  VkGraphicsPipelineCreateInfo create_info = {
      .sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
      .stageCount = 2,
      .pStages =
          (VkPipelineShaderStageCreateInfo[2]){
              {
                  .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                  .stage = VK_SHADER_STAGE_VERTEX_BIT,
                  .module = depth_vert_mod,
                  .pName = "vert",
              },
              {
                  .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                  .stage = VK_SHADER_STAGE_FRAGMENT_BIT,
                  .module = depth_frag_mod,
                  .pName = "frag",
              },
          },
      .pVertexInputState =
          &(VkPipelineVertexInputStateCreateInfo){
              .sType =
                  VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
          },
      .pInputAssemblyState =
          &(VkPipelineInputAssemblyStateCreateInfo){
              .sType =
                  VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
              .topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
          },
      .pViewportState =
          &(VkPipelineViewportStateCreateInfo){
              .sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
              .viewportCount = 1,
              .pViewports = &(VkViewport){0, 600.0f, 800.0f, -600.0f, 0, 1},
              .scissorCount = 1,
              .pScissors = &(VkRect2D){{0, 0}, {800, 600}},
          },
      .pRasterizationState =
          &(VkPipelineRasterizationStateCreateInfo){
              .sType =
                  VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
              .polygonMode = VK_POLYGON_MODE_FILL,
              .cullMode = VK_CULL_MODE_NONE,
              .frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE,
              .lineWidth = 1.0f,
          },
      .pMultisampleState =
          &(VkPipelineMultisampleStateCreateInfo){
              .sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
              .rasterizationSamples = VK_SAMPLE_COUNT_1_BIT,
          },
      .pColorBlendState =
          &(VkPipelineColorBlendStateCreateInfo){
              .sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
              .attachmentCount = 1,
              .pAttachments =
                  &(VkPipelineColorBlendAttachmentState){
                      .blendEnable = VK_FALSE,
                      .colorWriteMask =
                          VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                          VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT,
                  },
          },
      .pDepthStencilState =
          &(VkPipelineDepthStencilStateCreateInfo){
              .sType =
                  VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO,
          },
      .pDynamicState =
          &(VkPipelineDynamicStateCreateInfo){
              .sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO,
              .dynamicStateCount = 2,
              .pDynamicStates = (VkDynamicState[2]){VK_DYNAMIC_STATE_VIEWPORT,
                                                    VK_DYNAMIC_STATE_SCISSOR},
          },
      .layout = pipe_layout,
      .renderPass = pass,
  };
  err = tb_rnd_create_graphics_pipelines(render_system, 1, &create_info,
                                         "Depth Copy Pipeline", pipeline);
  TB_VK_CHECK_RET(err, "Failed to create depth copy pipeline", err);

  tb_rnd_destroy_shader(render_system, depth_vert_mod);
  tb_rnd_destroy_shader(render_system, depth_frag_mod);

  return err;
}

VkResult create_ocean_pipelines(RenderSystem *render_system,
                                VkRenderPass prepass, VkRenderPass pass,
                                VkPipelineLayout pipe_layout,
                                VkPipeline *prepass_pipeline,
                                VkPipeline *pipeline) {
  VkResult err = VK_SUCCESS;

  VkShaderModule oceanprepass_vert_mod = VK_NULL_HANDLE;
  VkShaderModule oceanprepass_frag_mod = VK_NULL_HANDLE;

  VkShaderModule ocean_vert_mod = VK_NULL_HANDLE;
  VkShaderModule ocean_frag_mod = VK_NULL_HANDLE;

  {
    VkShaderModuleCreateInfo create_info = {
        .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
    };

    create_info.codeSize = sizeof(oceanprepass_vert);
    create_info.pCode = (const uint32_t *)oceanprepass_vert;
    err = tb_rnd_create_shader(render_system, &create_info,
                               "Ocean Prepass Vert", &oceanprepass_vert_mod);
    TB_VK_CHECK_RET(err, "Failed to load ocean prepass vert shader module",
                    err);

    create_info.codeSize = sizeof(oceanprepass_frag);
    create_info.pCode = (const uint32_t *)oceanprepass_frag;
    err = tb_rnd_create_shader(render_system, &create_info,
                               "Ocean Prepass Frag", &oceanprepass_frag_mod);
    TB_VK_CHECK_RET(err, "Failed to load ocean prepass frag shader module",
                    err);

    create_info.codeSize = sizeof(ocean_vert);
    create_info.pCode = (const uint32_t *)ocean_vert;
    err = tb_rnd_create_shader(render_system, &create_info, "Ocean Vert",
                               &ocean_vert_mod);
    TB_VK_CHECK_RET(err, "Failed to load ocean vert shader module", err);

    create_info.codeSize = sizeof(ocean_frag);
    create_info.pCode = (const uint32_t *)ocean_frag;
    err = tb_rnd_create_shader(render_system, &create_info, "Ocean Frag",
                               &ocean_frag_mod);
    TB_VK_CHECK_RET(err, "Failed to load ocean frag shader module", err);
  }

  VkGraphicsPipelineCreateInfo create_info = {
      .sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
      .stageCount = 2,
      .pStages =
          (VkPipelineShaderStageCreateInfo[2]){
              {
                  .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                  .stage = VK_SHADER_STAGE_VERTEX_BIT,
                  .module = ocean_vert_mod,
                  .pName = "vert",
              },
              {
                  .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                  .stage = VK_SHADER_STAGE_FRAGMENT_BIT,
                  .module = ocean_frag_mod,
                  .pName = "frag",
              },
          },
      .pVertexInputState =
          &(VkPipelineVertexInputStateCreateInfo){
              .sType =
                  VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
              .vertexBindingDescriptionCount = 1,
              .pVertexBindingDescriptions =
                  (VkVertexInputBindingDescription[2]){
                      {0, sizeof(float) * 3, VK_VERTEX_INPUT_RATE_VERTEX},
                      {1, sizeof(float2), VK_VERTEX_INPUT_RATE_VERTEX},
                  },
              .vertexAttributeDescriptionCount = 1,
              .pVertexAttributeDescriptions =
                  (VkVertexInputAttributeDescription[2]){
                      {0, 0, VK_FORMAT_R32G32B32_SFLOAT, 0},
                      {1, 1, VK_FORMAT_R32G32_SFLOAT, 0},
                  },
          },
      .pInputAssemblyState =
          &(VkPipelineInputAssemblyStateCreateInfo){
              .sType =
                  VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
              .topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
          },
      .pViewportState =
          &(VkPipelineViewportStateCreateInfo){
              .sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
              .viewportCount = 1,
              .pViewports = &(VkViewport){0, 600.0f, 800.0f, -600.0f, 0, 1},
              .scissorCount = 1,
              .pScissors = &(VkRect2D){{0, 0}, {800, 600}},
          },
      .pRasterizationState =
          &(VkPipelineRasterizationStateCreateInfo){
              .sType =
                  VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
              .polygonMode = VK_POLYGON_MODE_FILL,
              .cullMode = VK_CULL_MODE_BACK_BIT,
              .frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE,
              .lineWidth = 1.0f,
          },
      .pMultisampleState =
          &(VkPipelineMultisampleStateCreateInfo){
              .sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
              .rasterizationSamples = VK_SAMPLE_COUNT_1_BIT,
          },
      .pColorBlendState =
          &(VkPipelineColorBlendStateCreateInfo){
              .sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
              .attachmentCount = 1,
              .pAttachments =
                  &(VkPipelineColorBlendAttachmentState){
                      .blendEnable = VK_TRUE,
                      .srcColorBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA,
                      .dstColorBlendFactor =
                          VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                      .colorBlendOp = VK_BLEND_OP_ADD,
                      .srcAlphaBlendFactor =
                          VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                      .dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO,
                      .alphaBlendOp = VK_BLEND_OP_ADD,
                      .colorWriteMask =
                          VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                          VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT,
                  },
          },
      .pDepthStencilState =
          &(VkPipelineDepthStencilStateCreateInfo){
              .sType =
                  VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO,
              .depthTestEnable = VK_TRUE,
              .depthWriteEnable = VK_FALSE,
              .depthCompareOp = VK_COMPARE_OP_GREATER_OR_EQUAL,
              .maxDepthBounds = 1.0f,
          },
      .pDynamicState =
          &(VkPipelineDynamicStateCreateInfo){
              .sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO,
              .dynamicStateCount = 2,
              .pDynamicStates = (VkDynamicState[2]){VK_DYNAMIC_STATE_VIEWPORT,
                                                    VK_DYNAMIC_STATE_SCISSOR},
          },
      .layout = pipe_layout,
      .renderPass = pass,
  };
  err = tb_rnd_create_graphics_pipelines(render_system, 1, &create_info,
                                         "Ocean Pipeline", pipeline);
  TB_VK_CHECK_RET(err, "Failed to create ocean pipeline", err);

  create_info.pStages =
      (VkPipelineShaderStageCreateInfo[2]){
          {
              .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
              .stage = VK_SHADER_STAGE_VERTEX_BIT,
              .module = oceanprepass_vert_mod,
              .pName = "vert",
          },
          {
              .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
              .stage = VK_SHADER_STAGE_FRAGMENT_BIT,
              .module = oceanprepass_frag_mod,
              .pName = "frag",
          },
      },
  create_info.pColorBlendState = &(VkPipelineColorBlendStateCreateInfo){
      .sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
  };
  create_info.pDepthStencilState =
      &(VkPipelineDepthStencilStateCreateInfo){
          .sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO,
          .depthTestEnable = VK_TRUE,
          .depthWriteEnable = VK_TRUE,
          .depthCompareOp = VK_COMPARE_OP_GREATER,
          .maxDepthBounds = 1.0f,
      },
  create_info.renderPass = prepass;

  err = tb_rnd_create_graphics_pipelines(render_system, 1, &create_info,
                                         "Ocean Prepass Pipeline",
                                         prepass_pipeline);
  TB_VK_CHECK_RET(err, "Failed to create ocean prepass pipeline", err);

  tb_rnd_destroy_shader(render_system, oceanprepass_vert_mod);
  tb_rnd_destroy_shader(render_system, oceanprepass_frag_mod);

  tb_rnd_destroy_shader(render_system, ocean_vert_mod);
  tb_rnd_destroy_shader(render_system, ocean_frag_mod);

  return err;
}

bool create_ocean_system(OceanSystem *self, const OceanSystemDescriptor *desc,
                         uint32_t system_dep_count,
                         System *const *system_deps) {
  // Find the necessary systems
  RenderSystem *render_system =
      tb_get_system(system_deps, system_dep_count, RenderSystem);
  TB_CHECK_RETURN(render_system,
                  "Failed to find render system which ocean depends on", false);
  MeshSystem *mesh_system =
      tb_get_system(system_deps, system_dep_count, MeshSystem);
  TB_CHECK_RETURN(mesh_system,
                  "Failed to find mesh system which ocean depends on", false);
  ViewSystem *view_system =
      tb_get_system(system_deps, system_dep_count, ViewSystem);
  TB_CHECK_RETURN(mesh_system,
                  "Failed to find view system which ocean depends on", false);

  *self = (OceanSystem){
      .render_system = render_system,
      .mesh_system = mesh_system,
      .view_system = view_system,
      .tmp_alloc = desc->tmp_alloc,
      .std_alloc = desc->std_alloc,
  };

  // Load the known glb that has the ocean mesh
  // Get qualified path to scene asset
  char *asset_path = tb_resolve_asset_path(self->tmp_alloc, "scenes/Ocean.glb");

  // Load glb off disk
  cgltf_data *data = tb_read_glb(self->std_alloc, asset_path);
  TB_CHECK_RETURN(data, "Failed to load glb", false);

  // Parse expected mesh from glb
  {
    const cgltf_mesh *ocean_mesh = &data->meshes[0];

    self->ocean_index_type = ocean_mesh->primitives->indices->stride == 2
                                 ? VK_INDEX_TYPE_UINT16
                                 : VK_INDEX_TYPE_UINT32;
    self->ocean_index_count = ocean_mesh->primitives->indices->count;

    uint32_t vertex_count = ocean_mesh->primitives->attributes->data->count;

    uint64_t index_size =
        self->ocean_index_count *
        (self->ocean_index_type == VK_INDEX_TYPE_UINT16 ? 2 : 4);
    uint64_t idx_padding = index_size % (sizeof(float) * 3);
    self->ocean_pos_offset = index_size + idx_padding;
    self->ocean_uv_offset =
        self->ocean_pos_offset +
        (vertex_count * (sizeof(float) * 6) + sizeof(float4));

    self->ocean_patch_mesh =
        tb_mesh_system_load_mesh(mesh_system, asset_path, ocean_mesh);
  }

  VkResult err = VK_SUCCESS;

  // Create Immutable Sampler
  {
    VkSamplerCreateInfo create_info = {
        .sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
        .magFilter = VK_FILTER_LINEAR,
        .minFilter = VK_FILTER_LINEAR,
        .mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR,
        .addressModeU = VK_SAMPLER_ADDRESS_MODE_REPEAT,
        .addressModeV = VK_SAMPLER_ADDRESS_MODE_REPEAT,
        .addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT,
        .anisotropyEnable = VK_FALSE,
        .maxAnisotropy = 1.0f,
        .maxLod = 1.0f,
        .borderColor = VK_BORDER_COLOR_FLOAT_OPAQUE_BLACK,
    };
    err = tb_rnd_create_sampler(render_system, &create_info, "Ocean Sampler",
                                &self->sampler);
    TB_VK_CHECK_RET(err, "Failed to create ocean sampler", err);
  }

  // Create depth descriptor set layout
  {
    VkDescriptorSetLayoutCreateInfo create_info = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .bindingCount = 2,
        .pBindings = (VkDescriptorSetLayoutBinding[2]){
            {
                .binding = 0,
                .descriptorCount = 1,
                .descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
                .stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT,
            },
            {
                .binding = 1,
                .descriptorCount = 1,
                .descriptorType = VK_DESCRIPTOR_TYPE_SAMPLER,
                .stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT,
                .pImmutableSamplers = &self->sampler,
            },
        }};
    err = tb_rnd_create_set_layout(render_system, &create_info,
                                   "Depth Descriptor Set Layout",
                                   &self->depth_set_layout);
    TB_VK_CHECK_RET(err, "Failed to create depth descriptor set layout", false);
  }

  // Create ocean descriptor set layout
  {
    VkDescriptorSetLayoutCreateInfo create_info = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .bindingCount = 3,
        .pBindings = (VkDescriptorSetLayoutBinding[3]){
            {
                .binding = 0,
                .descriptorCount = 1,
                .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
                .stageFlags = VK_SHADER_STAGE_VERTEX_BIT,
            },
            {
                .binding = 1,
                .descriptorCount = 1,
                .descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
                .stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT,
            },
            {
                .binding = 2,
                .descriptorCount = 1,
                .descriptorType = VK_DESCRIPTOR_TYPE_SAMPLER,
                .stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT,
                .pImmutableSamplers = &self->sampler,
            },
        }};
    err = tb_rnd_create_set_layout(render_system, &create_info,
                                   "Ocean Descriptor Set Layout",
                                   &self->set_layout);
    TB_VK_CHECK_RET(err, "Failed to create ocean descriptor set layout", false);
  }

  // Create depth pipeline layout
  {
    VkPipelineLayoutCreateInfo create_info = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        .setLayoutCount = 1,
        .pSetLayouts =
            (VkDescriptorSetLayout[1]){
                self->depth_set_layout,
            },
    };
    err = tb_rnd_create_pipeline_layout(render_system, &create_info,
                                        "Depth Pipeline Layout",
                                        &self->depth_pipe_layout);
    TB_VK_CHECK_RET(err, "Failed to create depth pipeline layout", false);
  }

  // Create ocean pipeline layout
  {
    VkPipelineLayoutCreateInfo create_info = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        .setLayoutCount = 2,
        .pSetLayouts =
            (VkDescriptorSetLayout[2]){
                self->set_layout,
                self->view_system->set_layout,
            },
        .pushConstantRangeCount = 1,
        .pPushConstantRanges =
            &(VkPushConstantRange){
                .size = sizeof(OceanPushConstants),
                .stageFlags = VK_SHADER_STAGE_VERTEX_BIT,
            },
    };
    err = tb_rnd_create_pipeline_layout(render_system, &create_info,
                                        "Ocean Pipeline Layout",
                                        &self->pipe_layout);
    TB_VK_CHECK_RET(err, "Failed to create ocean pipeline layout", false);
  }

  // Create depth copy pass
  {
    VkRenderPassCreateInfo create_info = {
        .sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO,
        .attachmentCount = 1,
        .pAttachments =
            &(VkAttachmentDescription){
                .format = VK_FORMAT_R32_SFLOAT,
                .samples = VK_SAMPLE_COUNT_1_BIT,
                .loadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
                .storeOp = VK_ATTACHMENT_STORE_OP_STORE,
                .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
                .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
                .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
                .finalLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
            },
        .subpassCount = 1,
        .pSubpasses =
            &(VkSubpassDescription){
                .pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS,
                .colorAttachmentCount = 1,
                .pColorAttachments =
                    &(VkAttachmentReference){
                        0,
                        VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
                    },
            },
        .pDependencies =
            &(VkSubpassDependency){
                .srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |
                                VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
                .dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |
                                VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
                .dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
            },
    };
    err = tb_rnd_create_render_pass(render_system, &create_info,
                                    "Depth Copy Pass", &self->depth_copy_pass);
    TB_VK_CHECK_RET(err, "Failed to create depth copy pass", false);
  }

  // Create depth pre pass for the ocean
  {
    VkRenderPassCreateInfo create_info = {
        .sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO,
        .attachmentCount = 1,
        .pAttachments =
            &(VkAttachmentDescription){
                .format = VK_FORMAT_D32_SFLOAT,
                .samples = VK_SAMPLE_COUNT_1_BIT,
                .loadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
                .storeOp = VK_ATTACHMENT_STORE_OP_STORE,
                .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
                .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
                .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
                .finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
            },
        .subpassCount = 1,
        .pSubpasses =
            &(VkSubpassDescription){
                .pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS,
                .pDepthStencilAttachment =
                    &(VkAttachmentReference){
                        0,
                        VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
                    },
            },
        .pDependencies =
            &(VkSubpassDependency){
                .srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |
                                VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
                .dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |
                                VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
                .dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
            },
    };
    err = tb_rnd_create_render_pass(render_system, &create_info,
                                    "Ocean Pre Pass", &self->ocean_prepass);
    TB_VK_CHECK_RET(err, "Failed to create ocean pre pass", false);
  }

  // Create render pass for the ocean
  {
    VkRenderPassCreateInfo create_info = {
        .sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO,
        .attachmentCount = 2,
        .pAttachments =
            (VkAttachmentDescription[2]){
                {
                    .format = render_system->render_thread->swapchain.format,
                    .samples = VK_SAMPLE_COUNT_1_BIT,
                    .loadOp = VK_ATTACHMENT_LOAD_OP_LOAD,
                    .storeOp = VK_ATTACHMENT_STORE_OP_STORE,
                    .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
                    .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
                    .initialLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
                    .finalLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
                },
                {
                    .format = VK_FORMAT_D32_SFLOAT,
                    .samples = VK_SAMPLE_COUNT_1_BIT,
                    .loadOp = VK_ATTACHMENT_LOAD_OP_LOAD,
                    .storeOp = VK_ATTACHMENT_STORE_OP_STORE,
                    .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
                    .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
                    .initialLayout =
                        VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
                    .finalLayout =
                        VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
                },
            },
        .subpassCount = 1,
        .pSubpasses =
            &(VkSubpassDescription){
                .pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS,
                .colorAttachmentCount = 1,
                .pColorAttachments =
                    &(VkAttachmentReference){
                        0,
                        VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
                    },
                .pDepthStencilAttachment =
                    &(VkAttachmentReference){
                        1,
                        VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
                    },
            },
        .pDependencies =
            &(VkSubpassDependency){
                .srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |
                                VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
                .dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |
                                VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
                .dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |
                                 VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
            },
    };
    err = tb_rnd_create_render_pass(render_system, &create_info, "Ocean Pass",
                                    &self->ocean_pass);
    TB_VK_CHECK_RET(err, "Failed to create ocean pass", false);
  }

  err = create_depth_pipeline(render_system, self->depth_copy_pass,
                              self->depth_pipe_layout, &self->depth_copy_pipe);
  TB_VK_CHECK_RET(err, "Failed to create depth copy pipeline", false);

  err = create_ocean_pipelines(render_system, self->ocean_prepass,
                               self->ocean_pass, self->pipe_layout,
                               &self->prepass_pipeline, &self->pipeline);
  TB_VK_CHECK_RET(err, "Failed to create ocean pipeline", false);

  // Create framebuffers for ocean pass and prepass
  {
    // TODO: Figure out a way to do this without referencing the render
    // thread directly

    // Depth Copy Pass
    {
      for (uint32_t i = 0; i < TB_MAX_FRAME_STATES; ++i) {
        VkFramebufferCreateInfo create_info = {
            .sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
            .renderPass = self->depth_copy_pass,
            .attachmentCount = 1,
            .pAttachments =
                &render_system->render_thread->frame_states[i].depth_copy_view,
            .width = render_system->render_thread->swapchain.width,
            .height = render_system->render_thread->swapchain.height,
            .layers = 1,
        };
        err = tb_rnd_create_framebuffer(render_system, &create_info,
                                        "Depth Copy Pass Framebuffer",
                                        &self->depth_copy_pass_framebuffers[i]);
      }
    }

    // Prepass
    {
      for (uint32_t i = 0; i < TB_MAX_FRAME_STATES; ++i) {
        VkFramebufferCreateInfo create_info = {
            .sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
            .renderPass = self->ocean_prepass,
            .attachmentCount = 1,
            .pAttachments = &render_system->render_thread->frame_states[i]
                                 .depth_buffer_view,
            .width = render_system->render_thread->swapchain.width,
            .height = render_system->render_thread->swapchain.height,
            .layers = 1,
        };
        err = tb_rnd_create_framebuffer(render_system, &create_info,
                                        "Ocean Pre Pass Framebuffer",
                                        &self->prepass_framebuffers[i]);
      }
    }
    // Ocean pass
    {
      for (uint32_t i = 0; i < TB_MAX_FRAME_STATES; ++i) {
        VkFramebufferCreateInfo create_info = {
            .sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
            .renderPass = self->ocean_pass,
            .attachmentCount = 2,
            .pAttachments =
                (VkImageView[2]){
                    render_system->render_thread->frame_states[i]
                        .swapchain_image_view,
                    render_system->render_thread->frame_states[i]
                        .depth_buffer_view,
                },
            .width = render_system->render_thread->swapchain.width,
            .height = render_system->render_thread->swapchain.height,
            .layers = 1,
        };
        err = tb_rnd_create_framebuffer(render_system, &create_info,
                                        "Ocean Pass Framebuffer",
                                        &self->framebuffers[i]);
      }
    }
  }

  // Register the depth copy pass first
  tb_rnd_register_pass(
      render_system, self->depth_copy_pass, self->depth_copy_pass_framebuffers,
      render_system->render_thread->swapchain.width,
      render_system->render_thread->swapchain.height, depth_copy_record);
  // Register the ocean passes (they use the same draw routine)
  tb_rnd_register_pass(
      render_system, self->ocean_prepass, self->prepass_framebuffers,
      render_system->render_thread->swapchain.width,
      render_system->render_thread->swapchain.height, ocean_pass_record);
  tb_rnd_register_pass(render_system, self->ocean_pass, self->framebuffers,
                       render_system->render_thread->swapchain.width,
                       render_system->render_thread->swapchain.height,
                       ocean_pass_record);

  self->ocean_geom_buffer =
      tb_mesh_system_get_gpu_mesh(mesh_system, self->ocean_patch_mesh);
  TB_CHECK_RETURN(self->ocean_geom_buffer, "Failed to get gpu buffer for mesh",
                  false);

  return true;
}

void destroy_ocean_system(OceanSystem *self) {
  tb_mesh_system_release_mesh_ref(self->mesh_system, self->ocean_patch_mesh);

  for (uint32_t i = 0; i < TB_MAX_FRAME_STATES; ++i) {
    tb_rnd_destroy_framebuffer(self->render_system, self->framebuffers[i]);
    tb_rnd_destroy_framebuffer(self->render_system,
                               self->prepass_framebuffers[i]);
    tb_rnd_destroy_framebuffer(self->render_system,
                               self->depth_copy_pass_framebuffers[i]);
    tb_rnd_destroy_descriptor_pool(self->render_system,
                                   self->ocean_pools[i].set_pool);
    tb_rnd_destroy_descriptor_pool(self->render_system,
                                   self->depth_pools[i].set_pool);
  }

  tb_rnd_destroy_sampler(self->render_system, self->sampler);

  tb_rnd_destroy_render_pass(self->render_system, self->depth_copy_pass);
  tb_rnd_destroy_pipe_layout(self->render_system, self->depth_pipe_layout);
  tb_rnd_destroy_set_layout(self->render_system, self->depth_set_layout);

  tb_rnd_destroy_pipeline(self->render_system, self->depth_copy_pipe);
  tb_rnd_destroy_pipeline(self->render_system, self->prepass_pipeline);
  tb_rnd_destroy_pipeline(self->render_system, self->pipeline);

  tb_rnd_destroy_render_pass(self->render_system, self->ocean_pass);
  tb_rnd_destroy_render_pass(self->render_system, self->ocean_prepass);
  tb_rnd_destroy_pipe_layout(self->render_system, self->pipe_layout);
  tb_rnd_destroy_set_layout(self->render_system, self->set_layout);

  *self = (OceanSystem){0};
}

void tick_ocean_system(OceanSystem *self, const SystemInput *input,
                       SystemOutput *output, float delta_seconds) {
  TracyCZoneNC(ctx, "Ocean System Tick", TracyCategoryColorRendering, true);

  EntityId *ocean_entities = tb_get_column_entity_ids(input, 0);

  const uint32_t ocean_count = tb_get_column_component_count(input, 0);
  const PackedComponentStore *oceans =
      tb_get_column_check_id(input, 0, 0, OceanComponentId);

  const uint32_t camera_count = tb_get_column_component_count(input, 1);
  const PackedComponentStore *cameras =
      tb_get_column_check_id(input, 1, 0, CameraComponentId);

  if (ocean_count == 0 || camera_count == 0) {
    TracyCZoneEnd(ctx);
    return;
  }

  VkResult err = VK_SUCCESS;
  RenderSystem *render_system = self->render_system;

  // Allocate and write descriptor sets for copying the depth buffer
  {
    // Allocate the one known descriptor set we need for this frame
    {
      VkDescriptorPoolCreateInfo pool_info = {
          .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
          .maxSets = 1,
          .poolSizeCount = 1,
          .pPoolSizes =
              &(VkDescriptorPoolSize){
                  .descriptorCount = 1,
                  .type = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
              },
      };
      err = tb_rnd_frame_desc_pool_tick(render_system, &pool_info,
                                        &self->depth_set_layout,
                                        self->depth_pools, 1);
      TB_VK_CHECK(err, "Failed to tick depth copy's descriptor pool");
    }

    VkDescriptorSet set =
        tb_rnd_frame_desc_pool_get_set(render_system, self->depth_pools, 0);

    // Write the descriptor set
    VkWriteDescriptorSet write = {
        .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
        .dstSet = set,
        .dstBinding = 0,
        .dstArrayElement = 0,
        .descriptorCount = 1,
        .descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
        .pImageInfo =
            &(VkDescriptorImageInfo){
                .imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                .imageView = render_system->render_thread
                                 ->frame_states[render_system->frame_idx]
                                 .depth_buffer_view,
            },
    };
    vkUpdateDescriptorSets(render_system->render_thread->device, 1, &write, 0,
                           NULL);
  }

  // Allocate and write all ocean descriptor sets
  {
    // Allocate all the descriptor sets
    {
      VkDescriptorPoolCreateInfo pool_info = {
          .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
          .maxSets = ocean_count,
          .poolSizeCount = 1,
          .pPoolSizes =
              &(VkDescriptorPoolSize){
                  .descriptorCount = ocean_count,
                  .type = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
              },
      };
      VkDescriptorSetLayout *layouts =
          tb_alloc_nm_tp(self->tmp_alloc, ocean_count, VkDescriptorSetLayout);
      for (uint32_t i = 0; i < ocean_count; ++i) {
        layouts[i] = self->set_layout;
      }
      err = tb_rnd_frame_desc_pool_tick(render_system, &pool_info, layouts,
                                        self->ocean_pools, ocean_count);
      TB_VK_CHECK(err, "Failed to tick ocean's descriptor pool");
    }

    // Just upload and write all views for now, they tend to be important anyway
    const uint32_t write_count = ocean_count; //* 2;
    VkWriteDescriptorSet *writes =
        tb_alloc_nm_tp(self->tmp_alloc, write_count, VkWriteDescriptorSet);
    VkDescriptorBufferInfo *buffer_info =
        tb_alloc_nm_tp(self->tmp_alloc, ocean_count, VkDescriptorBufferInfo);
    VkDescriptorImageInfo *image_info =
        tb_alloc_nm_tp(self->tmp_alloc, ocean_count, VkDescriptorImageInfo);
    TbHostBuffer *buffers =
        tb_alloc_nm_tp(self->tmp_alloc, ocean_count, TbHostBuffer);
    for (uint32_t oc_idx = 0; oc_idx < ocean_count; ++oc_idx) {
      const OceanComponent *ocean_comp =
          tb_get_component(oceans, oc_idx, OceanComponent);
      TbHostBuffer *buffer = &buffers[oc_idx];

      const uint32_t write_idx = oc_idx; // * 2;

      OceanData data = {
          .wave_count = ocean_comp->wave_count,
      };
      SDL_memcpy(data.wave, ocean_comp->waves,
                 data.wave_count * sizeof(OceanWave));

      // Write ocean data into the tmp buffer we know will wind up on the GPU
      err = tb_rnd_sys_alloc_tmp_host_buffer(render_system, sizeof(OceanData),
                                             0x40, buffer);
      TB_VK_CHECK(err, "Failed to make tmp host buffer allocation for ocean");

      // Copy view data to the allocated buffer
      SDL_memcpy(buffer->ptr, &data, sizeof(OceanData));

      VkBuffer tmp_gpu_buffer = tb_rnd_get_gpu_tmp_buffer(render_system);

      // Get the descriptor we want to write to
      VkDescriptorSet ocean_set = tb_rnd_frame_desc_pool_get_set(
          render_system, self->ocean_pools, oc_idx);

      buffer_info[oc_idx] = (VkDescriptorBufferInfo){
          .buffer = tmp_gpu_buffer,
          .offset = buffer->offset,
          .range = sizeof(OceanData),
      };

      // image_info[oc_idx] = (VkDescriptorImageInfo){
      //     .imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
      //     .imageView = render_system->render_thread
      //                      ->frame_states[render_system->frame_idx]
      //                      .depth_buffer_view,
      // };

      // Construct write descriptors
      writes[write_idx + 0] = (VkWriteDescriptorSet){
          .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
          .dstSet = ocean_set,
          .dstBinding = 0,
          .dstArrayElement = 0,
          .descriptorCount = 1,
          .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
          .pBufferInfo = &buffer_info[oc_idx],
      };
      // writes[write_idx + 1] = (VkWriteDescriptorSet){
      //     .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
      //     .dstSet = ocean_set,
      //     .dstBinding = 1,
      //     .dstArrayElement = 0,
      //     .descriptorCount = 1,
      //     .descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
      //     .pImageInfo = &image_info[oc_idx],
      // };
    }
    vkUpdateDescriptorSets(render_system->render_thread->device, write_count,
                           writes, 0, NULL);
  }

  // TODO: Make this less hacky
  const uint32_t width = render_system->render_thread->swapchain.width;
  const uint32_t height = render_system->render_thread->swapchain.height;

  // Issue draw to copy the depth buffer
  {
    DepthCopyBatch batch = {
        .pipeline = self->depth_copy_pipe,
        .layout = self->depth_pipe_layout,
        .viewport = {0, 0, width, height, 0, 1},
        .scissor = {{0, 0}, {width, height}},
        .depth_src_set =
            tb_rnd_frame_desc_pool_get_set(render_system, self->depth_pools, 0),
    };
    tb_rnd_issue_draw_batch(render_system, self->depth_copy_pass, 1,
                            sizeof(DepthCopyBatch), &batch);
  }

  // Draw the oceans and update components
  {
    // Copy the ocean component for output
    OceanComponent *out_oceans =
        tb_alloc_nm_tp(self->tmp_alloc, ocean_count, OceanComponent);
    SDL_memcpy(out_oceans, oceans->components,
               ocean_count * sizeof(OceanComponent));
    // Update time on all ocean components
    for (uint32_t ocean_idx = 0; ocean_idx < ocean_count; ++ocean_idx) {
      OceanComponent *ocean = &out_oceans[ocean_idx];
      ocean->time += delta_seconds;
    }

    // Max camera * ocean draw batches are required
    uint32_t batch_count = 0;
    const uint32_t batch_max = ocean_count * camera_count;
    OceanDrawBatch *batches =
        tb_alloc_nm_tp(self->tmp_alloc, batch_max, OceanDrawBatch);
    OceanDrawBatch *prepass_batches =
        tb_alloc_nm_tp(self->tmp_alloc, batch_max, OceanDrawBatch);

    for (uint32_t cam_idx = 0; cam_idx < camera_count; ++cam_idx) {
      const CameraComponent *camera =
          tb_get_component(cameras, cam_idx, CameraComponent);

      VkDescriptorSet view_set =
          tb_view_system_get_descriptor(self->view_system, camera->view_id);

      for (uint32_t ocean_idx = 0; ocean_idx < ocean_count; ++ocean_idx) {
        const OceanComponent *ocean_comp =
            tb_get_component(oceans, ocean_idx, OceanComponent);

        VkDescriptorSet ocean_set = tb_rnd_frame_desc_pool_get_set(
            self->render_system, self->ocean_pools, ocean_idx);

        // TODO: only if ocean is visible to camera
        batches[batch_count] = (OceanDrawBatch){
            .pipeline = self->pipeline,
            .layout = self->pipe_layout,
            .viewport = {0, 0, width, height, 0, 1},
            .scissor = {{0, 0}, {width, height}},
            .view_set = view_set,
            .ocean_set = ocean_set,
            .consts = (OceanPushConstants){ocean_comp->time},
            .geom_buffer = self->ocean_geom_buffer,
            .index_type = (VkIndexType)self->ocean_index_type,
            .index_count = self->ocean_index_count,
            .pos_offset = self->ocean_pos_offset,
            .uv_offset = self->ocean_uv_offset,
        };
        prepass_batches[batch_count] = (OceanDrawBatch){
            .pipeline = self->prepass_pipeline,
            .layout = self->pipe_layout,
            .viewport = {0, 0, width, height, 0, 1},
            .scissor = {{0, 0}, {width, height}},
            .view_set = view_set,
            .ocean_set = ocean_set,
            .consts = (OceanPushConstants){ocean_comp->time},
            .geom_buffer = self->ocean_geom_buffer,
            .index_type = (VkIndexType)self->ocean_index_type,
            .index_count = self->ocean_index_count,
            .pos_offset = self->ocean_pos_offset,
        };
        batch_count++;
      }
    }

    // Draw to the prepass and the ocean pass
    tb_rnd_issue_draw_batch(render_system, self->ocean_prepass, batch_count,
                            sizeof(OceanDrawBatch), prepass_batches);
    tb_rnd_issue_draw_batch(render_system, self->ocean_pass, batch_count,
                            sizeof(OceanDrawBatch), batches);

    // Report output (we've updated the time on the ocean component)
    output->set_count = 1;
    output->write_sets[0] = (SystemWriteSet){
        .id = OceanComponentId,
        .count = ocean_count,
        .components = (uint8_t *)out_oceans,
        .entities = ocean_entities,
    };
  }

  TracyCZoneEnd(ctx);
}

TB_DEFINE_SYSTEM(ocean, OceanSystem, OceanSystemDescriptor)

void tb_ocean_system_descriptor(SystemDescriptor *desc,
                                const OceanSystemDescriptor *ocean_desc) {
  *desc = (SystemDescriptor){
      .name = "Ocean",
      .size = sizeof(OceanSystem),
      .id = OceanSystemId,
      .desc = (InternalDescriptor)ocean_desc,
      .dep_count = 2,
      .deps[0] = {2, {OceanComponentId, TransformComponentId}},
      .deps[1] = {2, {CameraComponentId, TransformComponentId}},
      .system_dep_count = 3,
      .system_deps[0] = RenderSystemId,
      .system_deps[1] = MeshSystemId,
      .system_deps[2] = ViewSystemId,
      .create = tb_create_ocean_system,
      .destroy = tb_destroy_ocean_system,
      .tick = tb_tick_ocean_system,
  };
}
