name: Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        toolsets: [
          {host: [Windows, X64, self-hosted], preset: arm64-android-ninja-llvm},
          {host: [Linux, X64, self-hosted], preset: arm64-android-ninja-llvm},
          # Disabling mac host until a mac mini is self hosted
          #{host: [macos-12], preset: arm64-android-ninja-llvm, self-hosted: no},
        ]

    name: ${{matrix.toolsets.preset}} on ${{matrix.toolsets.host[0]}}
    runs-on: ${{matrix.toolsets.host}}

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'

    - name: Build Debug
      uses: lukka/run-cmake@v10
      with:
        configurePreset: '${{matrix.toolsets.preset}}'
        buildPreset: 'debug-${{matrix.toolsets.preset}}'

    - name: Build RelWithDebInfo
      uses: lukka/run-cmake@v10
      with:
        configurePreset: '${{matrix.toolsets.preset}}'
        buildPreset: 'relwithdebinfo-${{matrix.toolsets.preset}}'

    - name: Build Release
      uses: lukka/run-cmake@v10
      with:
        configurePreset: '${{matrix.toolsets.preset}}'
        buildPreset: 'release-${{matrix.toolsets.preset}}'
