name: Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        toolsets: [
          {host: [Windows, X64, self-hosted], preset: arm64-android-ninja-llvm},
          {host: [Linux, X64, self-hosted], preset: arm64-android-ninja-llvm},
          # Disabling mac host until a mac mini is self hosted
          #{host: [macos-12], preset: arm64-android-ninja-llvm, self-hosted: no},
        ]

    name: ${{matrix.toolsets.preset}} on ${{matrix.toolsets.host[0]}}
    runs-on: ${{matrix.toolsets.host}}

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'

    - name: Configure
      run: cmake --preset ${{matrix.toolsets.preset}} -DCOOK_ASSETS=OFF

    - name: Build Debug
      run: cmake --build --preset debug-${{matrix.toolsets.preset}}

    - name: Build RelWithDebInfo
      run: cmake --build --preset relwithdebinfo-${{matrix.toolsets.preset}}

    - name: Build Release
      run: cmake --build --preset release-${{matrix.toolsets.preset}}