name: Android

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

# Config to allow vcpkg to write dependency graph to the repo
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        toolsets: [
          {host: [Windows, X64, self-hosted], preset: arm64-android-ninja-llvm},
          {host: [Linux, X64, self-hosted], preset: arm64-android-ninja-llvm},
          {host: [macOS, ARM64, self-hosted], preset: arm64-android-ninja-llvm},
        ]

    name: ${{matrix.toolsets.preset}} on ${{matrix.toolsets.host[0]}}
    runs-on: ${{matrix.toolsets.host}}

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake --preset ${{matrix.toolsets.preset}} -DTB_COOK_ASSETS=OFF

    - name: Build Debug
      run: cmake --build --preset debug-${{matrix.toolsets.preset}}

    - name: Build RelWithDebInfo
      run: cmake --build --preset relwithdebinfo-${{matrix.toolsets.preset}}

    - name: Build Release
      run: cmake --build --preset release-${{matrix.toolsets.preset}}

    - name: Update Github Dependency Graph
      run: vcpkg install --dry-run --x-wait-for-lock