name: Steam Windows Deploy

on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: [Windows, X64, self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake --preset x64-windows-ninja-llvm -DFINAL=ON -DPROFILE_TRACY=OFF
    - name: Build Release
      run: cmake --build --preset release-x64-windows-ninja-llvm
    - uses: game-ci/steam-deploy@v1
      with:
        username: ${{ secrets.STEAM_USERNAME }}
        password: ${{ secrets.STEAM_PASSWORD }}
        configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
        ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
        ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
        appId: 2213960
        buildDescription: v0.1.0
        rootPath: build/x64/windows
        depot1Path: Release
        releaseBranch: steam-prerelease