name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

# Config to allow vcpkg to write dependency graph to the repo
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        toolsets: [
          {preset: x64-windows-ninja-llvm},
          {preset: x64-windows-static-ninja-llvm},
        ]

    name: ${{matrix.toolsets.preset}} on Windows
    runs-on: [Windows, X64, self-hosted]

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake --preset ${{matrix.toolsets.preset}} -DTB_COOK_ASSETS=OFF

    - name: Build Debug
      run: cmake --build --preset debug-${{matrix.toolsets.preset}}

    - name: Build RelWithDebInfo
      run: cmake --build --preset relwithdebinfo-${{matrix.toolsets.preset}}

    - name: Build Release
      run: cmake --build --preset release-${{matrix.toolsets.preset}}

    - name: Update Github Dependency Graph
      run: vcpkg.exe install --dry-run

  notify:
    needs: build
    name: Notify
    if: github.ref == 'refs/heads/main' # Only notify on commits to the main branch
    runs-on: [Windows, X64, self-hosted]
    steps:
      - name: Notify TheHighSeas
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: HoneybunchBuilder/thehighseas
          event-type: windows-engine
      - name: Notify Upland
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: HoneybunchBuilder/upland
          event-type: windows-engine
