name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        toolsets: [
          {host: [Windows, X64, self-hosted], preset: x64-windows-ninja-llvm},
          {host: [Windows, X64, self-hosted], preset: x64-windows-static-ninja-llvm},
          {host: [Windows, X64, self-hosted], preset: x64-mingw-ninja-gcc},
          {host: [Windows, X64, self-hosted], preset: x64-mingw-static-ninja-gcc},
          {host: [Windows, X64, self-hosted], preset: x64-windows-vs2022-llvm},
          {host: [Windows, X64, self-hosted], preset: x64-windows-static-vs2022-llvm},
        ]

    name: ${{matrix.toolsets.preset}} on ${{matrix.toolsets.host[0]}}
    runs-on: ${{matrix.toolsets.host}}

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'

    - name: Build Debug
      uses: lukka/run-cmake@v10
      with:
        configurePreset: '${{matrix.toolsets.preset}}'
        buildPreset: 'debug-${{matrix.toolsets.preset}}'

    - name: Build RelWithDebInfo
      uses: lukka/run-cmake@v10
      with:
        configurePreset: '${{matrix.toolsets.preset}}'
        buildPreset: 'relwithdebinfo-${{matrix.toolsets.preset}}'

    - name: Build Release
      uses: lukka/run-cmake@v10
      with:
        configurePreset: '${{matrix.toolsets.preset}}'
        buildPreset: 'release-${{matrix.toolsets.preset}}'
