name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        toolsets: [
          {host: [Windows, X64, self-hosted], preset: x64-windows-ninja-llvm},
          {host: [Windows, X64, self-hosted], preset: x64-windows-static-ninja-llvm},
          {host: [Windows, X64, self-hosted], preset: x64-mingw-ninja-gcc},
          {host: [Windows, X64, self-hosted], preset: x64-mingw-static-ninja-gcc},
          {host: [Windows, X64, self-hosted], preset: x64-windows-vs2022-llvm},
          {host: [Windows, X64, self-hosted], preset: x64-windows-static-vs2022-llvm},
        ]

    name: ${{matrix.toolsets.preset}} on ${{matrix.toolsets.host[0]}}
    runs-on: ${{matrix.toolsets.host}}

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake --preset ${{matrix.toolsets.preset}} -DCOOK_ASSETS=OFF

    - name: Build Debug
      run: cmake --build --preset debug-${{matrix.toolsets.preset}}

    - name: Build RelWithDebInfo
      run: cmake --build --preset relwithdebinfo-${{matrix.toolsets.preset}}

    - name: Build Release
      run: cmake --build --preset release-${{matrix.toolsets.preset}}