name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        toolsets: [
          {preset: x64-windows-ninja-llvm},
          {preset: x64-windows-static-ninja-llvm},
          {preset: x64-windows-vs2022-llvm},
          {preset: x64-windows-static-vs2022-llvm},
        ]

    name: ${{matrix.toolsets.preset}} on Windows}
    runs-on: [Windows, X64, self-hosted]

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake --preset ${{matrix.toolsets.preset}} -DCOOK_ASSETS=OFF

    - name: Build Debug
      run: cmake --build --preset debug-${{matrix.toolsets.preset}}

    - name: Build RelWithDebInfo
      run: cmake --build --preset relwithdebinfo-${{matrix.toolsets.preset}}

    - name: Build Release
      run: cmake --build --preset release-${{matrix.toolsets.preset}}

  notify:
    needs: build
    name: Notify TheHighSeas
    runs-on: [Windows, X64, self-hosted]
    steps:
      - name: Notify
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: HoneybunchBuilder/thehighseas
          event-type: windows-engine
